name: CI/CD pipeline
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: node:18.12.1-alpine3.15
    steps:
      - name: Github checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - name: Setup Fly.io config
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: cd backend && yarn install && flyctl deploy --remote-only --no-cache